version: "3.9"
services: 
    db: 
        container_name: "mysql"
        image: mysql:8.2.0
        ports: 
            - 3306:3306
        environment: 
            MYSQL_ROOT_PASSWORD: "123456"
            MYSQL_DATABASE: bytebankbd
            MYSQL_USER: alura
            MYSQL_PASSWORD: "123456"